version: '3'

services:
  backend:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env 
    command: sh -c "npm install && node ./server/seeder.js"
    networks:
      - app-network 
    
  frontend:
    build: ./frontend
    container_name: backend
    ports:
      - "3000:3000"
    networks:
      - app-network
    
networks:
  app-network:
    driver: bridge